name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create text file
        run: echo "test" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt

  download_and_display:
    needs: build_and_upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact
          path: ./downloaded

      - name: Display file contents
        run: cat ./downloaded/test.txt
